# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2

dependencies:
  pre:
    - gem -v
    # - rvm @global do gem uninstall bundler -ax
    # - rvm install rubygems 2.4.8 --force
    # - gem install bundler --pre
    - rbenv install 2.3.1 
    - bundle -v

# dependencies:
#     pre:                                                                                                                                                                       
#       - rvm install rubygems 2.4.8 --force                                                                                                                                     
#       - gem install bundler -v 1.11.2
jobs:
  build:

    # Specify the Xcode version to use
    macos:
      xcode: "9.2.0"

    steps:
      - checkout

       # Install Gems
      - run:
          name: Install Gems
          command: bundle install

      # Install CocoaPods
      - run:
          name: Install CocoaPods
          command: bundle exec pod install

      # Build the app and run tests
      - run:
          name: Build and run tests
          command: bundle exec fastlane travis
          environment:
            SCAN_DEVICE: iPhone 6
            SCAN_SCHEME: WebTests

      # Collect XML test results data to show in the UI,
      # and save the same XML files under test-results folder
      # in the Artifacts tab
      - store_test_results:
          path: test_output/report.xml
      - store_artifacts:
          path: /tmp/test-results
          destination: scan-test-results
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs
